/** ISO 3166-1 countries (plus Kosovo), sorted alphabetically by name, with dialing code and primary ISO 4217 currency. */
export interface Country {
  code: string;
  name: string;
  dialCode: string;
  currency: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afghanistan', dialCode: '+93', currency: 'AFN' },
  { code: 'AL', name: 'Albania', dialCode: '+355', currency: 'ALL' },
  { code: 'DZ', name: 'Algeria', dialCode: '+213', currency: 'DZD' },
  { code: 'AS', name: 'American Samoa', dialCode: '+1684', currency: 'USD' },
  { code: 'AD', name: 'Andorra', dialCode: '+376', currency: 'EUR' },
  { code: 'AO', name: 'Angola', dialCode: '+244', currency: 'AOA' },
  { code: 'AI', name: 'Anguilla', dialCode: '+1264', currency: 'XCD' },
  { code: 'AQ', name: 'Antarctica', dialCode: '+672', currency: 'USD' },
  { code: 'AG', name: 'Antigua and Barbuda', dialCode: '+1268', currency: 'XCD' },
  { code: 'AR', name: 'Argentina', dialCode: '+54', currency: 'ARS' },
  { code: 'AM', name: 'Armenia', dialCode: '+374', currency: 'AMD' },
  { code: 'AW', name: 'Aruba', dialCode: '+297', currency: 'AWG' },
  { code: 'AU', name: 'Australia', dialCode: '+61', currency: 'AUD' },
  { code: 'AT', name: 'Austria', dialCode: '+43', currency: 'EUR' },
  { code: 'AZ', name: 'Azerbaijan', dialCode: '+994', currency: 'AZN' },
  { code: 'BS', name: 'Bahamas', dialCode: '+1242', currency: 'BSD' },
  { code: 'BH', name: 'Bahrain', dialCode: '+973', currency: 'BHD' },
  { code: 'BD', name: 'Bangladesh', dialCode: '+880', currency: 'BDT' },
  { code: 'BB', name: 'Barbados', dialCode: '+1246', currency: 'BBD' },
  { code: 'BY', name: 'Belarus', dialCode: '+375', currency: 'BYN' },
  { code: 'BE', name: 'Belgium', dialCode: '+32', currency: 'EUR' },
  { code: 'BZ', name: 'Belize', dialCode: '+501', currency: 'BZD' },
  { code: 'BJ', name: 'Benin', dialCode: '+229', currency: 'XOF' },
  { code: 'BM', name: 'Bermuda', dialCode: '+1441', currency: 'BMD' },
  { code: 'BT', name: 'Bhutan', dialCode: '+975', currency: 'BTN' },
  { code: 'BO', name: 'Bolivia', dialCode: '+591', currency: 'BOB' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', dialCode: '+599', currency: 'USD' },
  { code: 'BA', name: 'Bosnia and Herzegovina', dialCode: '+387', currency: 'BAM' },
  { code: 'BW', name: 'Botswana', dialCode: '+267', currency: 'BWP' },
  { code: 'BV', name: 'Bouvet Island', dialCode: '+47', currency: 'NOK' },
  { code: 'BR', name: 'Brazil', dialCode: '+55', currency: 'BRL' },
  { code: 'IO', name: 'British Indian Ocean Territory', dialCode: '+246', currency: 'USD' },
  { code: 'BN', name: 'Brunei Darussalam', dialCode: '+673', currency: 'BND' },
  { code: 'BG', name: 'Bulgaria', dialCode: '+359', currency: 'BGN' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', currency: 'XOF' },
  { code: 'BI', name: 'Burundi', dialCode: '+257', currency: 'BIF' },
  { code: 'CV', name: 'Cabo Verde', dialCode: '+238', currency: 'CVE' },
  { code: 'KH', name: 'Cambodia', dialCode: '+855', currency: 'KHR' },
  { code: 'CM', name: 'Cameroon', dialCode: '+237', currency: 'XAF' },
  { code: 'CA', name: 'Canada', dialCode: '+1', currency: 'CAD' },
  { code: 'KY', name: 'Cayman Islands', dialCode: '+1345', currency: 'KYD' },
  { code: 'CF', name: 'Central African Republic', dialCode: '+236', currency: 'XAF' },
  { code: 'TD', name: 'Chad', dialCode: '+235', currency: 'XAF' },
  { code: 'CL', name: 'Chile', dialCode: '+56', currency: 'CLP' },
  { code: 'CN', name: 'China', dialCode: '+86', currency: 'CNY' },
  { code: 'CX', name: 'Christmas Island', dialCode: '+61', currency: 'AUD' },
  { code: 'CC', name: 'Cocos (Keeling) Islands', dialCode: '+61', currency: 'AUD' },
  { code: 'CO', name: 'Colombia', dialCode: '+57', currency: 'COP' },
  { code: 'KM', name: 'Comoros', dialCode: '+269', currency: 'KMF' },
  { code: 'CG', name: 'Congo', dialCode: '+242', currency: 'XAF' },
  { code: 'CD', name: 'Congo, Democratic Republic of the', dialCode: '+243', currency: 'CDF' },
  { code: 'CK', name: 'Cook Islands', dialCode: '+682', currency: 'NZD' },
  { code: 'CR', name: 'Costa Rica', dialCode: '+506', currency: 'CRC' },
  { code: 'HR', name: 'Croatia', dialCode: '+385', currency: 'EUR' },
  { code: 'CU', name: 'Cuba', dialCode: '+53', currency: 'CUP' },
  { code: 'CW', name: 'Curaçao', dialCode: '+599', currency: 'ANG' },
  { code: 'CY', name: 'Cyprus', dialCode: '+357', currency: 'EUR' },
  { code: 'CZ', name: 'Czechia', dialCode: '+420', currency: 'CZK' },
  { code: 'CI', name: "Côte d'Ivoire", dialCode: '+225', currency: 'XOF' },
  { code: 'DK', name: 'Denmark', dialCode: '+45', currency: 'DKK' },
  { code: 'DJ', name: 'Djibouti', dialCode: '+253', currency: 'DJF' },
  { code: 'DM', name: 'Dominica', dialCode: '+1767', currency: 'XCD' },
  { code: 'DO', name: 'Dominican Republic', dialCode: '+1809', currency: 'DOP' },
  { code: 'EC', name: 'Ecuador', dialCode: '+593', currency: 'USD' },
  { code: 'EG', name: 'Egypt', dialCode: '+20', currency: 'EGP' },
  { code: 'SV', name: 'El Salvador', dialCode: '+503', currency: 'USD' },
  { code: 'GQ', name: 'Equatorial Guinea', dialCode: '+240', currency: 'XAF' },
  { code: 'ER', name: 'Eritrea', dialCode: '+291', currency: 'ERN' },
  { code: 'EE', name: 'Estonia', dialCode: '+372', currency: 'EUR' },
  { code: 'SZ', name: 'Eswatini', dialCode: '+268', currency: 'SZL' },
  { code: 'ET', name: 'Ethiopia', dialCode: '+251', currency: 'ETB' },
  { code: 'FK', name: 'Falkland Islands (Malvinas)', dialCode: '+500', currency: 'FKP' },
  { code: 'FO', name: 'Faroe Islands', dialCode: '+298', currency: 'DKK' },
  { code: 'FJ', name: 'Fiji', dialCode: '+679', currency: 'FJD' },
  { code: 'FI', name: 'Finland', dialCode: '+358', currency: 'EUR' },
  { code: 'FR', name: 'France', dialCode: '+33', currency: 'EUR' },
  { code: 'GF', name: 'French Guiana', dialCode: '+594', currency: 'EUR' },
  { code: 'PF', name: 'French Polynesia', dialCode: '+689', currency: 'XPF' },
  { code: 'TF', name: 'French Southern Territories', dialCode: '+262', currency: 'EUR' },
  { code: 'GA', name: 'Gabon', dialCode: '+241', currency: 'XAF' },
  { code: 'GM', name: 'Gambia', dialCode: '+220', currency: 'GMD' },
  { code: 'GE', name: 'Georgia', dialCode: '+995', currency: 'GEL' },
  { code: 'DE', name: 'Germany', dialCode: '+49', currency: 'EUR' },
  { code: 'GH', name: 'Ghana', dialCode: '+233', currency: 'GHS' },
  { code: 'GI', name: 'Gibraltar', dialCode: '+350', currency: 'GIP' },
  { code: 'GR', name: 'Greece', dialCode: '+30', currency: 'EUR' },
  { code: 'GL', name: 'Greenland', dialCode: '+299', currency: 'DKK' },
  { code: 'GD', name: 'Grenada', dialCode: '+1473', currency: 'XCD' },
  { code: 'GP', name: 'Guadeloupe', dialCode: '+590', currency: 'EUR' },
  { code: 'GU', name: 'Guam', dialCode: '+1671', currency: 'USD' },
  { code: 'GT', name: 'Guatemala', dialCode: '+502', currency: 'GTQ' },
  { code: 'GG', name: 'Guernsey', dialCode: '+44', currency: 'GBP' },
  { code: 'GN', name: 'Guinea', dialCode: '+224', currency: 'GNF' },
  { code: 'GW', name: 'Guinea-Bissau', dialCode: '+245', currency: 'XOF' },
  { code: 'GY', name: 'Guyana', dialCode: '+592', currency: 'GYD' },
  { code: 'HT', name: 'Haiti', dialCode: '+509', currency: 'HTG' },
  { code: 'HM', name: 'Heard Island and McDonald Islands', dialCode: '+672', currency: 'AUD' },
  { code: 'VA', name: 'Holy See', dialCode: '+379', currency: 'EUR' },
  { code: 'HN', name: 'Honduras', dialCode: '+504', currency: 'HNL' },
  { code: 'HK', name: 'Hong Kong', dialCode: '+852', currency: 'HKD' },
  { code: 'HU', name: 'Hungary', dialCode: '+36', currency: 'HUF' },
  { code: 'IS', name: 'Iceland', dialCode: '+354', currency: 'ISK' },
  { code: 'IN', name: 'India', dialCode: '+91', currency: 'INR' },
  { code: 'ID', name: 'Indonesia', dialCode: '+62', currency: 'IDR' },
  { code: 'IR', name: 'Iran', dialCode: '+98', currency: 'IRR' },
  { code: 'IQ', name: 'Iraq', dialCode: '+964', currency: 'IQD' },
  { code: 'IE', name: 'Ireland', dialCode: '+353', currency: 'EUR' },
  { code: 'IM', name: 'Isle of Man', dialCode: '+44', currency: 'GBP' },
  { code: 'IL', name: 'Israel', dialCode: '+972', currency: 'ILS' },
  { code: 'IT', name: 'Italy', dialCode: '+39', currency: 'EUR' },
  { code: 'JM', name: 'Jamaica', dialCode: '+1876', currency: 'JMD' },
  { code: 'JP', name: 'Japan', dialCode: '+81', currency: 'JPY' },
  { code: 'JE', name: 'Jersey', dialCode: '+44', currency: 'GBP' },
  { code: 'JO', name: 'Jordan', dialCode: '+962', currency: 'JOD' },
  { code: 'KZ', name: 'Kazakhstan', dialCode: '+7', currency: 'KZT' },
  { code: 'KE', name: 'Kenya', dialCode: '+254', currency: 'KES' },
  { code: 'KI', name: 'Kiribati', dialCode: '+686', currency: 'AUD' },
  { code: 'KP', name: "Korea, Democratic People's Republic of", dialCode: '+850', currency: 'KPW' },
  { code: 'KR', name: 'Korea, Republic of', dialCode: '+82', currency: 'KRW' },
  { code: 'XK', name: 'Kosovo', dialCode: '+383', currency: 'EUR' },
  { code: 'KW', name: 'Kuwait', dialCode: '+965', currency: 'KWD' },
  { code: 'KG', name: 'Kyrgyzstan', dialCode: '+996', currency: 'KGS' },
  { code: 'LA', name: "Lao People's Democratic Republic", dialCode: '+856', currency: 'LAK' },
  { code: 'LV', name: 'Latvia', dialCode: '+371', currency: 'EUR' },
  { code: 'LB', name: 'Lebanon', dialCode: '+961', currency: 'LBP' },
  { code: 'LS', name: 'Lesotho', dialCode: '+266', currency: 'LSL' },
  { code: 'LR', name: 'Liberia', dialCode: '+231', currency: 'LRD' },
  { code: 'LY', name: 'Libya', dialCode: '+218', currency: 'LYD' },
  { code: 'LI', name: 'Liechtenstein', dialCode: '+423', currency: 'CHF' },
  { code: 'LT', name: 'Lithuania', dialCode: '+370', currency: 'EUR' },
  { code: 'LU', name: 'Luxembourg', dialCode: '+352', currency: 'EUR' },
  { code: 'MO', name: 'Macao', dialCode: '+853', currency: 'MOP' },
  { code: 'MG', name: 'Madagascar', dialCode: '+261', currency: 'MGA' },
  { code: 'MW', name: 'Malawi', dialCode: '+265', currency: 'MWK' },
  { code: 'MY', name: 'Malaysia', dialCode: '+60', currency: 'MYR' },
  { code: 'MV', name: 'Maldives', dialCode: '+960', currency: 'MVR' },
  { code: 'ML', name: 'Mali', dialCode: '+223', currency: 'XOF' },
  { code: 'MT', name: 'Malta', dialCode: '+356', currency: 'EUR' },
  { code: 'MH', name: 'Marshall Islands', dialCode: '+692', currency: 'USD' },
  { code: 'MQ', name: 'Martinique', dialCode: '+596', currency: 'EUR' },
  { code: 'MR', name: 'Mauritania', dialCode: '+222', currency: 'MRU' },
  { code: 'MU', name: 'Mauritius', dialCode: '+230', currency: 'MUR' },
  { code: 'YT', name: 'Mayotte', dialCode: '+262', currency: 'EUR' },
  { code: 'MX', name: 'Mexico', dialCode: '+52', currency: 'MXN' },
  { code: 'FM', name: 'Micronesia', dialCode: '+691', currency: 'USD' },
  { code: 'MD', name: 'Moldova', dialCode: '+373', currency: 'MDL' },
  { code: 'MC', name: 'Monaco', dialCode: '+377', currency: 'EUR' },
  { code: 'MN', name: 'Mongolia', dialCode: '+976', currency: 'MNT' },
  { code: 'ME', name: 'Montenegro', dialCode: '+382', currency: 'EUR' },
  { code: 'MS', name: 'Montserrat', dialCode: '+1664', currency: 'XCD' },
  { code: 'MA', name: 'Morocco', dialCode: '+212', currency: 'MAD' },
  { code: 'MZ', name: 'Mozambique', dialCode: '+258', currency: 'MZN' },
  { code: 'MM', name: 'Myanmar', dialCode: '+95', currency: 'MMK' },
  { code: 'NA', name: 'Namibia', dialCode: '+264', currency: 'NAD' },
  { code: 'NR', name: 'Nauru', dialCode: '+674', currency: 'AUD' },
  { code: 'NP', name: 'Nepal', dialCode: '+977', currency: 'NPR' },
  { code: 'NL', name: 'Netherlands', dialCode: '+31', currency: 'EUR' },
  { code: 'NC', name: 'New Caledonia', dialCode: '+687', currency: 'XPF' },
  { code: 'NZ', name: 'New Zealand', dialCode: '+64', currency: 'NZD' },
  { code: 'NI', name: 'Nicaragua', dialCode: '+505', currency: 'NIO' },
  { code: 'NE', name: 'Niger', dialCode: '+227', currency: 'XOF' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', currency: 'NGN' },
  { code: 'NU', name: 'Niue', dialCode: '+683', currency: 'NZD' },
  { code: 'NF', name: 'Norfolk Island', dialCode: '+672', currency: 'AUD' },
  { code: 'MK', name: 'North Macedonia', dialCode: '+389', currency: 'MKD' },
  { code: 'MP', name: 'Northern Mariana Islands', dialCode: '+1670', currency: 'USD' },
  { code: 'NO', name: 'Norway', dialCode: '+47', currency: 'NOK' },
  { code: 'OM', name: 'Oman', dialCode: '+968', currency: 'OMR' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92', currency: 'PKR' },
  { code: 'PW', name: 'Palau', dialCode: '+680', currency: 'USD' },
  { code: 'PS', name: 'Palestine, State of', dialCode: '+970', currency: 'ILS' },
  { code: 'PA', name: 'Panama', dialCode: '+507', currency: 'PAB' },
  { code: 'PG', name: 'Papua New Guinea', dialCode: '+675', currency: 'PGK' },
  { code: 'PY', name: 'Paraguay', dialCode: '+595', currency: 'PYG' },
  { code: 'PE', name: 'Peru', dialCode: '+51', currency: 'PEN' },
  { code: 'PH', name: 'Philippines', dialCode: '+63', currency: 'PHP' },
  { code: 'PN', name: 'Pitcairn', dialCode: '+64', currency: 'NZD' },
  { code: 'PL', name: 'Poland', dialCode: '+48', currency: 'PLN' },
  { code: 'PT', name: 'Portugal', dialCode: '+351', currency: 'EUR' },
  { code: 'PR', name: 'Puerto Rico', dialCode: '+1787', currency: 'USD' },
  { code: 'QA', name: 'Qatar', dialCode: '+974', currency: 'QAR' },
  { code: 'RO', name: 'Romania', dialCode: '+40', currency: 'RON' },
  { code: 'RU', name: 'Russian Federation', dialCode: '+7', currency: 'RUB' },
  { code: 'RW', name: 'Rwanda', dialCode: '+250', currency: 'RWF' },
  { code: 'RE', name: 'Réunion', dialCode: '+262', currency: 'EUR' },
  { code: 'BL', name: 'Saint Barthélemy', dialCode: '+590', currency: 'EUR' },
  { code: 'SH', name: 'Saint Helena, Ascension and Tristan da Cunha', dialCode: '+290', currency: 'SHP' },
  { code: 'KN', name: 'Saint Kitts and Nevis', dialCode: '+1869', currency: 'XCD' },
  { code: 'LC', name: 'Saint Lucia', dialCode: '+1758', currency: 'XCD' },
  { code: 'MF', name: 'Saint Martin (French part)', dialCode: '+590', currency: 'EUR' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', dialCode: '+508', currency: 'EUR' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '+1784', currency: 'XCD' },
  { code: 'WS', name: 'Samoa', dialCode: '+685', currency: 'WST' },
  { code: 'SM', name: 'San Marino', dialCode: '+378', currency: 'EUR' },
  { code: 'ST', name: 'Sao Tome and Principe', dialCode: '+239', currency: 'STN' },
  { code: 'SA', name: 'Saudi Arabia', dialCode: '+966', currency: 'SAR' },
  { code: 'SN', name: 'Senegal', dialCode: '+221', currency: 'XOF' },
  { code: 'RS', name: 'Serbia', dialCode: '+381', currency: 'RSD' },
  { code: 'SC', name: 'Seychelles', dialCode: '+248', currency: 'SCR' },
  { code: 'SL', name: 'Sierra Leone', dialCode: '+232', currency: 'SLE' },
  { code: 'SG', name: 'Singapore', dialCode: '+65', currency: 'SGD' },
  { code: 'SX', name: 'Sint Maarten (Dutch part)', dialCode: '+1721', currency: 'ANG' },
  { code: 'SK', name: 'Slovakia', dialCode: '+421', currency: 'EUR' },
  { code: 'SI', name: 'Slovenia', dialCode: '+386', currency: 'EUR' },
  { code: 'SB', name: 'Solomon Islands', dialCode: '+677', currency: 'SBD' },
  { code: 'SO', name: 'Somalia', dialCode: '+252', currency: 'SOS' },
  { code: 'ZA', name: 'South Africa', dialCode: '+27', currency: 'ZAR' },
  { code: 'GS', name: 'South Georgia and the South Sandwich Islands', dialCode: '+500', currency: 'GBP' },
  { code: 'SS', name: 'South Sudan', dialCode: '+211', currency: 'SSP' },
  { code: 'ES', name: 'Spain', dialCode: '+34', currency: 'EUR' },
  { code: 'LK', name: 'Sri Lanka', dialCode: '+94', currency: 'LKR' },
  { code: 'SD', name: 'Sudan', dialCode: '+249', currency: 'SDG' },
  { code: 'SR', name: 'Suriname', dialCode: '+597', currency: 'SRD' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', dialCode: '+47', currency: 'NOK' },
  { code: 'SE', name: 'Sweden', dialCode: '+46', currency: 'SEK' },
  { code: 'CH', name: 'Switzerland', dialCode: '+41', currency: 'CHF' },
  { code: 'SY', name: 'Syrian Arab Republic', dialCode: '+963', currency: 'SYP' },
  { code: 'TW', name: 'Taiwan', dialCode: '+886', currency: 'TWD' },
  { code: 'TJ', name: 'Tajikistan', dialCode: '+992', currency: 'TJS' },
  { code: 'TZ', name: 'Tanzania, United Republic of', dialCode: '+255', currency: 'TZS' },
  { code: 'TH', name: 'Thailand', dialCode: '+66', currency: 'THB' },
  { code: 'TL', name: 'Timor-Leste', dialCode: '+670', currency: 'USD' },
  { code: 'TG', name: 'Togo', dialCode: '+228', currency: 'XOF' },
  { code: 'TK', name: 'Tokelau', dialCode: '+690', currency: 'NZD' },
  { code: 'TO', name: 'Tonga', dialCode: '+676', currency: 'TOP' },
  { code: 'TT', name: 'Trinidad and Tobago', dialCode: '+1868', currency: 'TTD' },
  { code: 'TN', name: 'Tunisia', dialCode: '+216', currency: 'TND' },
  { code: 'TM', name: 'Turkmenistan', dialCode: '+993', currency: 'TMT' },
  { code: 'TC', name: 'Turks and Caicos Islands', dialCode: '+1649', currency: 'USD' },
  { code: 'TV', name: 'Tuvalu', dialCode: '+688', currency: 'AUD' },
  { code: 'TR', name: 'Türkiye', dialCode: '+90', currency: 'TRY' },
  { code: 'UG', name: 'Uganda', dialCode: '+256', currency: 'UGX' },
  { code: 'UA', name: 'Ukraine', dialCode: '+380', currency: 'UAH' },
  { code: 'AE', name: 'United Arab Emirates', dialCode: '+971', currency: 'AED' },
  { code: 'GB', name: 'United Kingdom', dialCode: '+44', currency: 'GBP' },
  { code: 'US', name: 'United States', dialCode: '+1', currency: 'USD' },
  { code: 'UM', name: 'United States Minor Outlying Islands', dialCode: '+1', currency: 'USD' },
  { code: 'UY', name: 'Uruguay', dialCode: '+598', currency: 'UYU' },
  { code: 'UZ', name: 'Uzbekistan', dialCode: '+998', currency: 'UZS' },
  { code: 'VU', name: 'Vanuatu', dialCode: '+678', currency: 'VUV' },
  { code: 'VE', name: 'Venezuela', dialCode: '+58', currency: 'VES' },
  { code: 'VN', name: 'Viet Nam', dialCode: '+84', currency: 'VND' },
  { code: 'VG', name: 'Virgin Islands (British)', dialCode: '+1284', currency: 'USD' },
  { code: 'VI', name: 'Virgin Islands (U.S.)', dialCode: '+1340', currency: 'USD' },
  { code: 'WF', name: 'Wallis and Futuna', dialCode: '+681', currency: 'XPF' },
  { code: 'EH', name: 'Western Sahara', dialCode: '+212', currency: 'MAD' },
  { code: 'YE', name: 'Yemen', dialCode: '+967', currency: 'YER' },
  { code: 'ZM', name: 'Zambia', dialCode: '+260', currency: 'ZMW' },
  { code: 'ZW', name: 'Zimbabwe', dialCode: '+263', currency: 'ZWG' },
  { code: 'AX', name: 'Åland Islands', dialCode: '+358', currency: 'EUR' },
];

export const COUNTRY_BY_CODE: Record<string, Country> = Object.fromEntries(COUNTRIES.map((c) => [c.code, c]));

/**
 * The language the surfaces show country names in. Each application sets it when the person changes language (next to
 * `setTrLang`), so the 200-odd country names never have to live in a phrase pack: the platform asks the runtime for
 * the name in that language and falls back to the English name it ships with.
 */
let displayLanguage = 'en';
export function setDisplayLanguage(lang: string): void {
  displayLanguage = (lang || 'en').trim() || 'en';
  regionNames = null;
}
export function getDisplayLanguage(): string {
  return displayLanguage;
}
let regionNames: { of: (code: string) => string | undefined } | null = null;
function regionNamesFor(lang: string): { of: (code: string) => string | undefined } | null {
  if (regionNames) return regionNames;
  try {
    const DisplayNames = (globalThis as { Intl?: { DisplayNames?: new (l: string[], o: { type: string }) => { of: (c: string) => string | undefined } } }).Intl?.DisplayNames;
    if (!DisplayNames) return null;
    regionNames = new DisplayNames([lang, 'en'], { type: 'region' });
    return regionNames;
  } catch {
    return null;
  }
}

/** The country's name in the display language ("Congo - Kinshasa" in English, « Congo-Kinshasa » in French). */
export function countryName(code?: string | null): string {
  if (!code) return '';
  const c = code.toUpperCase();
  const known = COUNTRY_BY_CODE[c];
  const fallback = known?.name ?? code;
  // Only a country the platform ships is asked of the runtime: an unknown code must come back as it was given, not as
  // the runtime's "unknown region" wording.
  if (!known || displayLanguage.startsWith('en')) return fallback;
  const localised = regionNamesFor(displayLanguage)?.of(c);
  return localised && localised !== c ? localised : fallback;
}
