import type { CurrencyInfo } from './money';

/** All ISO 4217 currencies, sorted by code. Rates are approximate defaults; admins refresh live rates from a provider. */
export const ALL_CURRENCIES: CurrencyInfo[] = [
  { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'AED', decimals: 2, rateToBase: 3.67 },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', decimals: 2, rateToBase: 70 },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'ALL', decimals: 2, rateToBase: 92 },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', decimals: 2, rateToBase: 390 },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ANG', decimals: 2, rateToBase: 1.79 },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', decimals: 2, rateToBase: 900 },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', decimals: 2, rateToBase: 1050 },
  { code: 'AUD', name: 'Australian Dollar', symbol: '$', decimals: 2, rateToBase: 1.55 },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'AWG', decimals: 2, rateToBase: 1.79 },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', decimals: 2, rateToBase: 1.7 },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', decimals: 2, rateToBase: 1.8 },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', decimals: 2, rateToBase: 2 },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', decimals: 2, rateToBase: 120 },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'BGN', decimals: 2, rateToBase: 1.8 },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BHD', decimals: 3, rateToBase: 0.376 },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'BIF', decimals: 0, rateToBase: 2900 },
  { code: 'BMD', name: 'Bermudan Dollar', symbol: '$', decimals: 2, rateToBase: 1 },
  { code: 'BND', name: 'Brunei Dollar', symbol: '$', decimals: 2, rateToBase: 1.34 },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', decimals: 2, rateToBase: 6.9 },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', decimals: 2, rateToBase: 5.6 },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', decimals: 2, rateToBase: 1 },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'BTN', decimals: 2, rateToBase: 84 },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', decimals: 2, rateToBase: 13.5 },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'BYN', decimals: 2, rateToBase: 3.27 },
  { code: 'BZD', name: 'Belize Dollar', symbol: '$', decimals: 2, rateToBase: 2 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: '$', decimals: 2, rateToBase: 1.38 },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'CDF', decimals: 2, rateToBase: 2850 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', decimals: 2, rateToBase: 0.88 },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', decimals: 0, rateToBase: 950 },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', decimals: 2, rateToBase: 7.2 },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', decimals: 2, rateToBase: 4200 },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', decimals: 2, rateToBase: 510 },
  { code: 'CUC', name: 'Cuban Convertible Peso', symbol: '$', decimals: 2, rateToBase: 1 },
  { code: 'CUP', name: 'Cuban Peso', symbol: '$', decimals: 2, rateToBase: 24 },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: 'CVE', decimals: 2, rateToBase: 101 },
  { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', decimals: 2, rateToBase: 23.5 },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'DJF', decimals: 0, rateToBase: 178 },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', decimals: 2, rateToBase: 6.9 },
  { code: 'DOP', name: 'Dominican Peso', symbol: '$', decimals: 2, rateToBase: 60 },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'DZD', decimals: 2, rateToBase: 134 },
  { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', decimals: 2, rateToBase: 50 },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'ERN', decimals: 2, rateToBase: 15 },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'ETB', decimals: 2, rateToBase: 125 },
  { code: 'EUR', name: 'Euro', symbol: '€', decimals: 2, rateToBase: 0.92 },
  { code: 'FJD', name: 'Fijian Dollar', symbol: '$', decimals: 2, rateToBase: 2.25 },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', decimals: 2, rateToBase: 0.79 },
  { code: 'GBP', name: 'British Pound', symbol: '£', decimals: 2, rateToBase: 0.79 },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', decimals: 2, rateToBase: 2.75 },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', decimals: 2, rateToBase: 15.5 },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', decimals: 2, rateToBase: 0.79 },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'GMD', decimals: 2, rateToBase: 70 },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', decimals: 0, rateToBase: 8600 },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', decimals: 2, rateToBase: 7.7 },
  { code: 'GYD', name: 'Guyanaese Dollar', symbol: '$', decimals: 2, rateToBase: 209 },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: '$', decimals: 2, rateToBase: 7.8 },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', decimals: 2, rateToBase: 25.5 },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', decimals: 2, rateToBase: 6.9 },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'HTG', decimals: 2, rateToBase: 131 },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', decimals: 2, rateToBase: 370 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', decimals: 2, rateToBase: 16000 },
  { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', decimals: 2, rateToBase: 3.65 },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', decimals: 2, rateToBase: 84 },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'IQD', decimals: 3, rateToBase: 1310 },
  { code: 'IRR', name: 'Iranian Rial', symbol: 'IRR', decimals: 2, rateToBase: 42000 },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', decimals: 0, rateToBase: 138 },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: '$', decimals: 2, rateToBase: 157 },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JOD', decimals: 3, rateToBase: 0.709 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', decimals: 0, rateToBase: 150 },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KES', decimals: 2, rateToBase: 129 },
  { code: 'KGS', name: 'Kyrgyz Som', symbol: '⃀', decimals: 2, rateToBase: 86 },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', decimals: 2, rateToBase: 4100 },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', decimals: 0, rateToBase: 453 },
  { code: 'KPW', name: 'North Korean Won', symbol: '₩', decimals: 2, rateToBase: 900 },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', decimals: 0, rateToBase: 1380 },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KWD', decimals: 3, rateToBase: 0.307 },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', decimals: 2, rateToBase: 0.83 },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', decimals: 2, rateToBase: 490 },
  { code: 'LAK', name: 'Laotian Kip', symbol: '₭', decimals: 2, rateToBase: 21800 },
  { code: 'LBP', name: 'Lebanese Pound', symbol: 'L£', decimals: 2, rateToBase: 89500 },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', decimals: 2, rateToBase: 295 },
  { code: 'LRD', name: 'Liberian Dollar', symbol: '$', decimals: 2, rateToBase: 190 },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'LSL', decimals: 2, rateToBase: 18 },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'LYD', decimals: 3, rateToBase: 4.85 },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', decimals: 2, rateToBase: 9.9 },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'MDL', decimals: 2, rateToBase: 18 },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', decimals: 2, rateToBase: 4600 },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'MKD', decimals: 2, rateToBase: 56.5 },
  { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', decimals: 2, rateToBase: 2100 },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', decimals: 2, rateToBase: 3400 },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP', decimals: 2, rateToBase: 8.03 },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'MRU', decimals: 2, rateToBase: 40 },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: 'Rs', decimals: 2, rateToBase: 46 },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'MVR', decimals: 2, rateToBase: 15.4 },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MWK', decimals: 2, rateToBase: 1735 },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', decimals: 2, rateToBase: 19.5 },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', decimals: 2, rateToBase: 4.4 },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MZN', decimals: 2, rateToBase: 64 },
  { code: 'NAD', name: 'Namibian Dollar', symbol: '$', decimals: 2, rateToBase: 18 },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', decimals: 2, rateToBase: 1550 },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', decimals: 2, rateToBase: 36.8 },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', decimals: 2, rateToBase: 10.8 },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'Rs', decimals: 2, rateToBase: 134 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: '$', decimals: 2, rateToBase: 1.7 },
  { code: 'OMR', name: 'Omani Rial', symbol: 'OMR', decimals: 3, rateToBase: 0.385 },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'PAB', decimals: 2, rateToBase: 1 },
  { code: 'PEN', name: 'Peruvian Sol', symbol: 'PEN', decimals: 2, rateToBase: 3.75 },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'PGK', decimals: 2, rateToBase: 4 },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', decimals: 2, rateToBase: 57 },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: 'Rs', decimals: 2, rateToBase: 278 },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', decimals: 2, rateToBase: 4 },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', decimals: 0, rateToBase: 7800 },
  { code: 'QAR', name: 'Qatari Riyal', symbol: 'QAR', decimals: 2, rateToBase: 3.64 },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', decimals: 2, rateToBase: 4.6 },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'RSD', decimals: 2, rateToBase: 108 },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', decimals: 2, rateToBase: 92 },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'RF', decimals: 0, rateToBase: 1360 },
  { code: 'SAR', name: 'Saudi Riyal', symbol: 'SAR', decimals: 2, rateToBase: 3.75 },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', decimals: 2, rateToBase: 8.4 },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: 'SCR', decimals: 2, rateToBase: 14 },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'SDG', decimals: 2, rateToBase: 600 },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', decimals: 2, rateToBase: 10.6 },
  { code: 'SGD', name: 'Singapore Dollar', symbol: '$', decimals: 2, rateToBase: 1.34 },
  { code: 'SHP', name: 'St. Helena Pound', symbol: '£', decimals: 2, rateToBase: 0.79 },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'SLE', decimals: 2, rateToBase: 22.5 },
  { code: 'SLL', name: 'Sierra Leonean Leone (1964—2022)', symbol: 'SLL', decimals: 2, rateToBase: 22500 },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'SOS', decimals: 2, rateToBase: 571 },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', decimals: 2, rateToBase: 35 },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', decimals: 2, rateToBase: 1300 },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'Db', decimals: 2, rateToBase: 22.5 },
  { code: 'SVC', name: 'Salvadoran Colón', symbol: 'SVC', decimals: 2, rateToBase: 8.75 },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£', decimals: 2, rateToBase: 13000 },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'SZL', decimals: 2, rateToBase: 18 },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', decimals: 2, rateToBase: 34 },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'TJS', decimals: 2, rateToBase: 10.7 },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'TMT', decimals: 2, rateToBase: 3.5 },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'TND', decimals: 3, rateToBase: 3.1 },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', decimals: 2, rateToBase: 2.35 },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', decimals: 2, rateToBase: 34 },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: '$', decimals: 2, rateToBase: 6.8 },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: '$', decimals: 2, rateToBase: 32 },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TZS', decimals: 2, rateToBase: 2700 },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', decimals: 2, rateToBase: 41 },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'UGX', decimals: 0, rateToBase: 3700 },
  { code: 'USD', name: 'US Dollar', symbol: '$', decimals: 2, rateToBase: 1 },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$', decimals: 2, rateToBase: 42 },
  { code: 'UZS', name: 'Uzbekistani Som', symbol: 'UZS', decimals: 2, rateToBase: 12800 },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'VES', decimals: 2, rateToBase: 40 },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', decimals: 0, rateToBase: 25000 },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VUV', decimals: 0, rateToBase: 119 },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WST', decimals: 2, rateToBase: 2.8 },
  { code: 'XAF', name: 'Central African CFA Franc', symbol: 'FCFA', decimals: 0, rateToBase: 603 },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', decimals: 2, rateToBase: 2.7 },
  { code: 'XCG', name: 'Caribbean guilder', symbol: 'Cg.', decimals: 2, rateToBase: 1 },
  { code: 'XDR', name: 'Special Drawing Rights', symbol: 'XDR', decimals: 2, rateToBase: 1 },
  { code: 'XOF', name: 'West African CFA Franc', symbol: 'F CFA', decimals: 0, rateToBase: 603 },
  { code: 'XPF', name: 'CFP Franc', symbol: 'CFPF', decimals: 0, rateToBase: 110 },
  { code: 'XSU', name: 'Sucre', symbol: 'XSU', decimals: 2, rateToBase: 1 },
  { code: 'YER', name: 'Yemeni Rial', symbol: 'YER', decimals: 2, rateToBase: 250 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', decimals: 2, rateToBase: 18 },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', decimals: 2, rateToBase: 27 },
  { code: 'ZWG', name: 'Zimbabwean Gold', symbol: 'ZWG', decimals: 2, rateToBase: 13.5 },
  { code: 'ZWL', name: 'Zimbabwean Dollar (2009–2024)', symbol: 'ZWL', decimals: 2, rateToBase: 322 },
];

export const CURRENCY_BY_CODE: Record<string, CurrencyInfo> = Object.fromEntries(ALL_CURRENCIES.map((c) => [c.code, c]));
