export const ar: Record<string, string> = {
  'nav.dashboard': 'لوحة التحكم', 'nav.move': 'تحويل الأموال', 'nav.send': 'إرسال الأموال', 'nav.scan': 'مسح ودفع', 'nav.receive': 'استلام', 'nav.requests': 'الطلبات والروابط', 'nav.addMoney': 'إضافة رصيد', 'nav.withdraw': 'سحب', 'nav.agents': 'الوكلاء والنقد', 'nav.remittance': 'التحويلات الدولية', 'nav.exchange': 'صرف العملات', 'nav.cards': 'البطاقات الافتراضية', 'nav.bills': 'دفع الفواتير', 'nav.topup': 'شحن الهاتف', 'nav.giftCards': 'بطاقات الهدايا', 'nav.p2p': 'تداول P2P', 'nav.transactions': 'المعاملات', 'nav.referrals': 'الإحالات', 'nav.support': 'الدعم', 'nav.settings': 'الإعدادات', 'nav.merchant': 'أدوات التاجر', 'nav.agentTools': 'أدوات الوكيل', 'nav.logout': 'تسجيل الخروج',
  'common.amount': 'المبلغ', 'common.currency': 'العملة', 'common.note': 'ملاحظة', 'common.continue': 'متابعة', 'common.confirm': 'تأكيد', 'common.cancel': 'إلغاء', 'common.save': 'حفظ', 'common.fee': 'الرسوم', 'common.total': 'الإجمالي', 'common.status': 'الحالة', 'common.date': 'التاريخ', 'common.search': 'بحث', 'common.loading': 'جارٍ التحميل…', 'common.balance': 'الرصيد', 'common.pin': 'رمز المعاملة', 'common.copy': 'نسخ', 'common.copied': 'تم النسخ!', 'common.share': 'مشاركة', 'common.back': 'رجوع', 'common.all': 'الكل', 'common.none': 'لا يوجد شيء بعد',
  'auth.signIn': 'تسجيل الدخول', 'auth.signUp': 'إنشاء حساب', 'auth.email': 'البريد الإلكتروني', 'auth.phone': 'رقم الهاتف', 'auth.password': 'كلمة المرور', 'auth.identifier': 'البريد أو الهاتف', 'auth.forgot': 'نسيت كلمة المرور؟', 'auth.otpLogin': 'الدخول برمز لمرة واحدة', 'auth.noAccount': 'ليس لديك حساب؟', 'auth.haveAccount': 'لديك حساب بالفعل؟', 'auth.fullName': 'الاسم الكامل', 'auth.role': 'نوع الحساب', 'auth.role.user': 'شخصي', 'auth.role.merchant': 'تاجر / شركة', 'auth.role.agent': 'وكيل / بائع تجزئة', 'auth.referral': 'رمز الإحالة (اختياري)', 'auth.country': 'الدولة', 'auth.sendCode': 'إرسال الرمز', 'auth.code': 'رمز التحقق',
  'dash.welcome': 'مرحباً بعودتك، {name}', 'dash.totalBalance': 'إجمالي الرصيد', 'dash.quickActions': 'إجراءات سريعة', 'dash.recent': 'النشاط الأخير', 'dash.viewAll': 'عرض الكل',
  'send.title': 'إرسال الأموال', 'send.to': 'المستلم (@المعرف أو البريد أو الهاتف)', 'send.review': 'مراجعة التحويل', 'send.success': 'تم الإرسال!', 'receive.title': 'استلام الأموال', 'receive.subtitle': 'دع الآخرين يمسحون هذا الرمز للدفع لك', 'receive.requestAmount': 'طلب مبلغ محدد', 'scan.title': 'امسح للدفع', 'scan.hint': 'وجّه الكاميرا نحو رمز QR الخاص بـ BitriPay', 'scan.paste': 'أو الصق محتوى الرمز / رابط الدفع',
  'addMoney.title': 'إضافة رصيد', 'addMoney.method': 'طريقة الدفع', 'addMoney.card': 'بطاقة ائتمان / خصم', 'addMoney.mobileMoney': 'المحفظة الإلكترونية', 'addMoney.bank': 'تحويل بنكي', 'addMoney.agent': 'نقداً لدى وكيل', 'withdraw.title': 'سحب إلى البنك', 'tx.in': 'مستلم', 'tx.out': 'مرسل',
  'settings.profile': 'الملف الشخصي', 'settings.security': 'الأمان', 'settings.kyc': 'التحقق من الهوية', 'settings.language': 'اللغة', 'settings.theme': 'الوضع الداكن', 'settings.2fa': 'المصادقة الثنائية', 'settings.pin': 'رمز المعاملة', 'settings.password': 'تغيير كلمة المرور',
  'landing.hero': 'المال يتحرك بسرعة المسح', 'landing.sub': 'أرسل واستلم واقبل المدفوعات عبر رموز QR. أضف رصيداً بالبطاقة أو المحفظة الإلكترونية، ادفع الفواتير، أرسل التحويلات الدولية، تداول العملات وأصدر بطاقات افتراضية – كل ذلك من محفظة BitriPay واحدة.', 'landing.getStarted': 'ابدأ مجاناً', 'landing.merchant': 'قبول المدفوعات',
};

