export const bn: Record<string, string> = {
  'nav.dashboard': 'ড্যাশবোর্ড', 'nav.send': 'টাকা পাঠান', 'nav.scan': 'স্ক্যান করে পরিশোধ', 'nav.receive': 'গ্রহণ করুন', 'nav.requests': 'অনুরোধ ও লিংক', 'nav.addMoney': 'টাকা যোগ করুন', 'nav.withdraw': 'উত্তোলন', 'nav.agents': 'এজেন্ট ও নগদ', 'nav.remittance': 'রেমিট্যান্স', 'nav.exchange': 'মুদ্রা বিনিময়', 'nav.cards': 'ভার্চুয়াল কার্ড', 'nav.bills': 'বিল পরিশোধ', 'nav.topup': 'মোবাইল রিচার্জ', 'nav.giftCards': 'গিফট কার্ড', 'nav.p2p': 'P2P ট্রেডিং', 'nav.transactions': 'লেনদেন', 'nav.referrals': 'রেফারেল', 'nav.support': 'সহায়তা', 'nav.settings': 'সেটিংস', 'nav.merchant': 'মার্চেন্ট টুল', 'nav.agentTools': 'এজেন্ট টুল', 'nav.logout': 'সাইন আউট',
  'common.amount': 'পরিমাণ', 'common.currency': 'মুদ্রা', 'common.note': 'নোট', 'common.continue': 'চালিয়ে যান', 'common.confirm': 'নিশ্চিত করুন', 'common.cancel': 'বাতিল', 'common.save': 'সংরক্ষণ', 'common.fee': 'ফি', 'common.total': 'মোট', 'common.status': 'অবস্থা', 'common.date': 'তারিখ', 'common.search': 'খুঁজুন', 'common.loading': 'লোড হচ্ছে…', 'common.balance': 'ব্যালেন্স', 'common.pin': 'লেনদেন পিন', 'common.copy': 'কপি', 'common.copied': 'কপি হয়েছে!', 'common.share': 'শেয়ার', 'common.back': 'ফিরে যান', 'common.all': 'সব', 'common.none': 'এখনও কিছু নেই',
  'auth.signIn': 'সাইন ইন', 'auth.signUp': 'অ্যাকাউন্ট খুলুন', 'auth.email': 'ইমেইল', 'auth.phone': 'ফোন নম্বর', 'auth.password': 'পাসওয়ার্ড', 'auth.identifier': 'ইমেইল বা ফোন', 'auth.forgot': 'পাসওয়ার্ড ভুলে গেছেন?', 'auth.otpLogin': 'ওয়ান-টাইম কোড দিয়ে সাইন ইন', 'auth.noAccount': 'অ্যাকাউন্ট নেই?', 'auth.haveAccount': 'ইতিমধ্যে অ্যাকাউন্ট আছে?', 'auth.fullName': 'পুরো নাম', 'auth.role': 'অ্যাকাউন্টের ধরন', 'auth.role.user': 'ব্যক্তিগত', 'auth.role.merchant': 'মার্চেন্ট / ব্যবসা', 'auth.role.agent': 'এজেন্ট / খুচরা বিক্রেতা', 'auth.referral': 'রেফারেল কোড (ঐচ্ছিক)', 'auth.country': 'দেশ', 'auth.sendCode': 'কোড পাঠান', 'auth.code': 'যাচাইকরণ কোড',
  'dash.welcome': 'স্বাগতম, {name}', 'dash.totalBalance': 'মোট ব্যালেন্স', 'dash.quickActions': 'দ্রুত কাজ', 'dash.recent': 'সাম্প্রতিক কার্যকলাপ', 'dash.viewAll': 'সব দেখুন',
  'send.title': 'টাকা পাঠান', 'send.to': 'প্রাপক (@ট্যাগ, ইমেইল বা ফোন)', 'send.review': 'ট্রান্সফার পর্যালোচনা', 'send.success': 'টাকা পাঠানো হয়েছে!', 'receive.title': 'টাকা গ্রহণ', 'receive.subtitle': 'অন্যরা এই কোড স্ক্যান করে আপনাকে পরিশোধ করতে পারবে', 'receive.requestAmount': 'নির্দিষ্ট পরিমাণ অনুরোধ করুন', 'scan.title': 'পরিশোধ করতে স্ক্যান করুন', 'scan.hint': 'ক্যামেরা BitriPay QR কোডের দিকে ধরুন', 'scan.paste': 'অথবা QR কনটেন্ট / পেমেন্ট লিংক পেস্ট করুন',
  'addMoney.title': 'টাকা যোগ করুন', 'addMoney.method': 'পেমেন্ট পদ্ধতি', 'addMoney.card': 'ডেবিট / ক্রেডিট কার্ড', 'addMoney.mobileMoney': 'মোবাইল মানি', 'addMoney.bank': 'ব্যাংক ট্রান্সফার', 'addMoney.agent': 'এজেন্টের কাছে নগদ', 'withdraw.title': 'ব্যাংকে উত্তোলন', 'tx.in': 'প্রাপ্ত', 'tx.out': 'প্রেরিত',
  'settings.profile': 'প্রোফাইল', 'settings.security': 'নিরাপত্তা', 'settings.kyc': 'পরিচয় যাচাই', 'settings.language': 'ভাষা', 'settings.theme': 'ডার্ক মোড', 'settings.2fa': 'দুই-ধাপ যাচাইকরণ', 'settings.pin': 'লেনদেন পিন', 'settings.password': 'পাসওয়ার্ড পরিবর্তন',
  'landing.hero': 'এক স্ক্যানের গতিতে টাকা', 'landing.sub': 'QR কোডে টাকা পাঠান, গ্রহণ করুন ও পেমেন্ট নিন। কার্ড বা মোবাইল মানিতে টাকা যোগ করুন, বিল দিন, রেমিট্যান্স পাঠান, মুদ্রা বিনিময় করুন ও ভার্চুয়াল কার্ড নিন – সব এক BitriPay ওয়ালেট থেকে।', 'landing.getStarted': 'বিনামূল্যে শুরু করুন', 'landing.merchant': 'পেমেন্ট গ্রহণ করুন',
};

