export const fr: Record<string, string> = {
  'nav.dashboard': 'Tableau de bord', 'nav.move': 'Déplacer de l\'argent', 'nav.send': "Envoyer de l'argent", 'nav.scan': 'Scanner & payer', 'nav.receive': 'Recevoir', 'nav.requests': 'Demandes & liens', 'nav.addMoney': 'Ajouter des fonds', 'nav.withdraw': 'Retirer', 'nav.agents': 'Agents & espèces', 'nav.remittance': 'Transfert international', 'nav.exchange': 'Change', 'nav.cards': 'Cartes virtuelles', 'nav.bills': 'Paiement de factures', 'nav.topup': 'Recharge mobile', 'nav.giftCards': 'Cartes cadeaux', 'nav.p2p': 'Échange P2P', 'nav.transactions': 'Transactions', 'nav.referrals': 'Parrainage', 'nav.assist': 'Centre de commande', 'nav.support': 'Assistance', 'nav.settings': 'Paramètres', 'nav.merchant': 'Outils marchand', 'nav.centre': 'Centre de commande', 'nav.qrCentre': 'Centre QR', 'nav.developer': 'Portail développeur', 'nav.savings': 'Épargne et objectifs', 'nav.fxTools': 'Taux et contrats à terme', 'nav.credit': 'Solvabilité', 'nav.subscriptions': 'Abonnements', 'nav.banks': 'Banques liées', 'pwa.offline': 'Vous êtes hors ligne. Les soldes affichés sont le dernier état synchronisé ; les codes et promesses hors ligne continuent de fonctionner et se synchronisent au retour du réseau.', 'pwa.lastSync': 'Dernière synchro', 'nav.agentTools': 'Outils agent', 'nav.logout': 'Se déconnecter',
  'common.amount': 'Montant', 'common.currency': 'Devise', 'common.note': 'Note', 'common.continue': 'Continuer', 'common.confirm': 'Confirmer', 'common.cancel': 'Annuler', 'common.save': 'Enregistrer', 'common.fee': 'Frais', 'common.total': 'Total', 'common.status': 'Statut', 'common.date': 'Date', 'common.search': 'Rechercher', 'common.loading': 'Chargement…', 'common.balance': 'Solde', 'common.pin': 'Code PIN de transaction', 'common.copy': 'Copier', 'common.copied': 'Copié !', 'common.share': 'Partager', 'common.back': 'Retour', 'common.all': 'Tout', 'common.none': 'Rien pour le moment',
  'auth.signIn': 'Se connecter', 'auth.signUp': 'Créer un compte', 'auth.email': 'E-mail', 'auth.phone': 'Numéro de téléphone', 'auth.password': 'Mot de passe', 'auth.identifier': 'E-mail ou téléphone', 'auth.forgot': 'Mot de passe oublié ?', 'auth.otpLogin': 'Connexion par code unique', 'auth.noAccount': 'Pas de compte ?', 'auth.haveAccount': 'Vous avez déjà un compte ?', 'auth.fullName': 'Nom complet', 'auth.role': 'Type de compte', 'auth.role.user': 'Personnel', 'auth.role.merchant': 'Marchand / entreprise', 'auth.role.agent': 'Agent / détaillant', 'auth.referral': 'Code de parrainage (optionnel)', 'auth.country': 'Pays', 'auth.sendCode': 'Envoyer le code', 'auth.code': 'Code de vérification',
  'dash.welcome': 'Bon retour, {name}', 'dash.totalBalance': 'Solde total', 'dash.quickActions': 'Actions rapides', 'dash.recent': 'Activité récente', 'dash.viewAll': 'Tout voir',
  'send.title': "Envoyer de l'argent", 'send.to': 'Destinataire (@tag, e-mail ou téléphone)', 'send.review': 'Vérifier le transfert', 'send.success': 'Argent envoyé !', 'receive.title': "Recevoir de l'argent", 'receive.subtitle': 'Laissez les autres scanner ce code pour vous payer', 'receive.requestAmount': 'Demander un montant précis', 'scan.title': 'Scanner pour payer', 'scan.hint': 'Pointez votre caméra vers un QR code BitriPay', 'scan.paste': 'Ou collez le contenu du QR / lien de paiement',
  'addMoney.title': 'Ajouter des fonds', 'addMoney.method': 'Moyen de paiement', 'addMoney.card': 'Carte bancaire', 'addMoney.mobileMoney': 'Mobile money', 'addMoney.bank': 'Virement bancaire', 'addMoney.agent': 'Espèces chez un agent', 'withdraw.title': 'Retirer vers la banque', 'tx.in': 'Reçu', 'tx.out': 'Envoyé',
  'settings.profile': 'Profil', 'settings.security': 'Sécurité', 'settings.kyc': "Vérification d'identité", 'settings.language': 'Langue', 'settings.theme': 'Mode sombre', 'settings.2fa': 'Authentification à deux facteurs', 'settings.pin': 'Code PIN de transaction', 'settings.password': 'Changer le mot de passe',
  'landing.hero': "L'argent à la vitesse d'un scan", 'landing.sub': 'Envoyez, recevez et acceptez des paiements par QR code. Ajoutez des fonds par carte ou mobile money, payez vos factures, envoyez des transferts internationaux, échangez des devises et créez des cartes virtuelles – depuis un seul portefeuille BitriPay.', 'landing.getStarted': 'Commencer gratuitement', 'landing.merchant': 'Accepter des paiements',
};

