export const hi: Record<string, string> = {
  'nav.dashboard': 'डैशबोर्ड', 'nav.send': 'पैसे भेजें', 'nav.scan': 'स्कैन करें और भुगतान करें', 'nav.receive': 'प्राप्त करें', 'nav.requests': 'अनुरोध और लिंक', 'nav.addMoney': 'पैसे जोड़ें', 'nav.withdraw': 'निकालें', 'nav.agents': 'एजेंट और नकद', 'nav.remittance': 'विदेशी प्रेषण', 'nav.exchange': 'मुद्रा विनिमय', 'nav.cards': 'वर्चुअल कार्ड', 'nav.bills': 'बिल भुगतान', 'nav.topup': 'मोबाइल रिचार्ज', 'nav.giftCards': 'गिफ्ट कार्ड', 'nav.p2p': 'P2P ट्रेडिंग', 'nav.transactions': 'लेन-देन', 'nav.referrals': 'रेफ़रल', 'nav.support': 'सहायता', 'nav.settings': 'सेटिंग्स', 'nav.merchant': 'मर्चेंट टूल', 'nav.agentTools': 'एजेंट टूल', 'nav.logout': 'साइन आउट',
  'common.amount': 'राशि', 'common.currency': 'मुद्रा', 'common.note': 'नोट', 'common.continue': 'जारी रखें', 'common.confirm': 'पुष्टि करें', 'common.cancel': 'रद्द करें', 'common.save': 'सहेजें', 'common.fee': 'शुल्क', 'common.total': 'कुल', 'common.status': 'स्थिति', 'common.date': 'तारीख', 'common.search': 'खोजें', 'common.loading': 'लोड हो रहा है…', 'common.balance': 'बैलेंस', 'common.pin': 'लेन-देन पिन', 'common.copy': 'कॉपी', 'common.copied': 'कॉपी हो गया!', 'common.share': 'साझा करें', 'common.back': 'वापस', 'common.all': 'सभी', 'common.none': 'अभी यहाँ कुछ नहीं है',
  'auth.signIn': 'साइन इन', 'auth.signUp': 'खाता बनाएँ', 'auth.email': 'ईमेल', 'auth.phone': 'फ़ोन नंबर', 'auth.password': 'पासवर्ड', 'auth.identifier': 'ईमेल या फ़ोन', 'auth.forgot': 'पासवर्ड भूल गए?', 'auth.otpLogin': 'वन-टाइम कोड से साइन इन करें', 'auth.noAccount': 'खाता नहीं है?', 'auth.haveAccount': 'पहले से खाता है?', 'auth.fullName': 'पूरा नाम', 'auth.role': 'खाते का प्रकार', 'auth.role.user': 'व्यक्तिगत', 'auth.role.merchant': 'व्यापारी / व्यवसाय', 'auth.role.agent': 'एजेंट / रिटेलर', 'auth.referral': 'रेफ़रल कोड (वैकल्पिक)', 'auth.country': 'देश', 'auth.sendCode': 'कोड भेजें', 'auth.code': 'सत्यापन कोड',
  'dash.welcome': 'वापसी पर स्वागत है, {name}', 'dash.totalBalance': 'कुल बैलेंस', 'dash.quickActions': 'त्वरित क्रियाएँ', 'dash.recent': 'हाल की गतिविधि', 'dash.viewAll': 'सभी देखें',
  'send.title': 'पैसे भेजें', 'send.to': 'प्राप्तकर्ता (@टैग, ईमेल या फ़ोन)', 'send.review': 'ट्रांसफ़र की समीक्षा', 'send.success': 'पैसे भेज दिए गए!', 'receive.title': 'पैसे प्राप्त करें', 'receive.subtitle': 'दूसरों को भुगतान के लिए यह कोड स्कैन करने दें', 'receive.requestAmount': 'निश्चित राशि का अनुरोध करें', 'scan.title': 'भुगतान के लिए स्कैन करें', 'scan.hint': 'अपना कैमरा BitriPay QR कोड पर रखें', 'scan.paste': 'या QR सामग्री / भुगतान लिंक पेस्ट करें',
  'addMoney.title': 'पैसे जोड़ें', 'addMoney.method': 'भुगतान विधि', 'addMoney.card': 'डेबिट / क्रेडिट कार्ड', 'addMoney.mobileMoney': 'मोबाइल मनी', 'addMoney.bank': 'बैंक ट्रांसफ़र', 'addMoney.agent': 'एजेंट के पास नकद', 'withdraw.title': 'बैंक में निकालें', 'tx.in': 'प्राप्त', 'tx.out': 'भेजा गया',
  'settings.profile': 'प्रोफ़ाइल', 'settings.security': 'सुरक्षा', 'settings.kyc': 'पहचान सत्यापन', 'settings.language': 'भाषा', 'settings.theme': 'डार्क मोड', 'settings.2fa': 'दो-चरणीय प्रमाणीकरण', 'settings.pin': 'लेन-देन पिन', 'settings.password': 'पासवर्ड बदलें',
  'landing.hero': 'एक स्कैन की रफ़्तार से पैसा', 'landing.sub': 'QR कोड से पैसे भेजें, प्राप्त करें और स्वीकार करें। कार्ड या मोबाइल मनी से पैसे जोड़ें, बिल भरें, विदेश पैसे भेजें, मुद्रा बदलें और वर्चुअल कार्ड बनाएँ – सब एक ही BitriPay वॉलेट से।', 'landing.getStarted': 'मुफ़्त शुरू करें', 'landing.merchant': 'भुगतान स्वीकार करें',
};

