export const sw: Record<string, string> = {
  'nav.dashboard': 'Dashibodi', 'nav.send': 'Tuma pesa', 'nav.scan': 'Skani na ulipe', 'nav.receive': 'Pokea', 'nav.requests': 'Maombi na viungo', 'nav.addMoney': 'Weka pesa', 'nav.withdraw': 'Toa pesa', 'nav.agents': 'Mawakala na fedha taslimu', 'nav.remittance': 'Tuma nje ya nchi', 'nav.exchange': 'Badilisha sarafu', 'nav.cards': 'Kadi pepe', 'nav.bills': 'Lipa bili', 'nav.topup': 'Nunua muda wa maongezi', 'nav.giftCards': 'Kadi za zawadi', 'nav.p2p': 'Biashara ya P2P', 'nav.transactions': 'Miamala', 'nav.referrals': 'Rufaa', 'nav.support': 'Msaada', 'nav.settings': 'Mipangilio', 'nav.merchant': 'Zana za mfanyabiashara', 'nav.agentTools': 'Zana za wakala', 'nav.logout': 'Ondoka',
  'common.amount': 'Kiasi', 'common.currency': 'Sarafu', 'common.note': 'Maelezo', 'common.continue': 'Endelea', 'common.confirm': 'Thibitisha', 'common.cancel': 'Ghairi', 'common.save': 'Hifadhi', 'common.fee': 'Ada', 'common.total': 'Jumla', 'common.status': 'Hali', 'common.date': 'Tarehe', 'common.search': 'Tafuta', 'common.loading': 'Inapakia…', 'common.balance': 'Salio', 'common.pin': 'PIN ya muamala', 'common.copy': 'Nakili', 'common.copied': 'Imenakiliwa!', 'common.share': 'Shiriki', 'common.back': 'Rudi', 'common.all': 'Zote', 'common.none': 'Hakuna kitu bado',
  'auth.signIn': 'Ingia', 'auth.signUp': 'Fungua akaunti', 'auth.email': 'Barua pepe', 'auth.phone': 'Nambari ya simu', 'auth.password': 'Nenosiri', 'auth.identifier': 'Barua pepe au simu', 'auth.forgot': 'Umesahau nenosiri?', 'auth.otpLogin': 'Ingia kwa msimbo wa mara moja', 'auth.noAccount': 'Huna akaunti?', 'auth.haveAccount': 'Una akaunti tayari?', 'auth.fullName': 'Jina kamili', 'auth.role': 'Aina ya akaunti', 'auth.role.user': 'Binafsi', 'auth.role.merchant': 'Mfanyabiashara', 'auth.role.agent': 'Wakala / muuzaji', 'auth.referral': 'Msimbo wa rufaa (hiari)', 'auth.country': 'Nchi', 'auth.sendCode': 'Tuma msimbo', 'auth.code': 'Msimbo wa uthibitisho',
  'dash.welcome': 'Karibu tena, {name}', 'dash.totalBalance': 'Salio la jumla', 'dash.quickActions': 'Vitendo vya haraka', 'dash.recent': 'Shughuli za hivi karibuni', 'dash.viewAll': 'Ona zote',
  'send.title': 'Tuma pesa', 'send.to': 'Mpokeaji (@tag, barua pepe au simu)', 'send.review': 'Kagua uhamisho', 'send.success': 'Pesa zimetumwa!', 'receive.title': 'Pokea pesa', 'receive.subtitle': 'Waache wengine waskani msimbo huu ili wakulipe', 'receive.requestAmount': 'Omba kiasi maalum', 'scan.title': 'Skani ili ulipe', 'scan.hint': 'Elekeza kamera kwenye msimbo wa QR wa BitriPay', 'scan.paste': 'Au bandika maudhui ya QR / kiungo cha malipo',
  'addMoney.title': 'Weka pesa', 'addMoney.method': 'Njia ya malipo', 'addMoney.card': 'Kadi ya benki', 'addMoney.mobileMoney': 'Pesa za simu', 'addMoney.bank': 'Uhamisho wa benki', 'addMoney.agent': 'Fedha taslimu kwa wakala', 'withdraw.title': 'Toa kwenda benki', 'tx.in': 'Imepokelewa', 'tx.out': 'Imetumwa',
  'settings.profile': 'Wasifu', 'settings.security': 'Usalama', 'settings.kyc': 'Uthibitisho wa utambulisho', 'settings.language': 'Lugha', 'settings.theme': 'Hali ya giza', 'settings.2fa': 'Uthibitisho wa hatua mbili', 'settings.pin': 'PIN ya muamala', 'settings.password': 'Badilisha nenosiri',
  'landing.hero': 'Pesa inasonga kwa kasi ya skani', 'landing.sub': 'Tuma, pokea na ukubali malipo kwa misimbo ya QR. Weka pesa kwa kadi au pesa za simu, lipa bili, tuma pesa nje ya nchi, badilisha sarafu na utoe kadi pepe – yote kutoka mkoba mmoja wa BitriPay.', 'landing.getStarted': 'Anza bure', 'landing.merchant': 'Kubali malipo',
};

