import { chromium } from 'playwright-core';
const base = 'http://127.0.0.1:5173';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => {
  if (m.type() === 'error') errors.push(m.text());
});
// admin: configure MTN Ghana collection number
const admin = await browser.newPage({ viewport: { width: 1360, height: 900 } });
admin.on('pageerror', (e) => errors.push('admin: ' + e.message));
await admin.goto('http://127.0.0.1:5174/login');
await admin.fill('input:not([type=password])', 'admin@bitripay.local');
await admin.fill('input[type=password]', 'Admin123!');
await admin.click('form button.btn');
await admin.waitForSelector('text=Analytics dashboard');
await admin.goto('http://127.0.0.1:5174/mobile-money');
await admin.waitForSelector('text=all world operators');
await admin.locator('.card select').last().selectOption('GH');
await admin.waitForTimeout(600);
await admin.screenshot({ path: 'shots/rails-admin-operators.png' });
const row = admin.locator('tr', { hasText: 'MTN Mobile Money' }).first();
await row.locator('button:has-text("Configure")').click();
await admin.fill('input[placeholder="0244000000"]', '0244000000');
await admin.fill('input[placeholder="BitriPay Ltd"]', 'BitriPay Ghana');
await admin.click('.modal button:has-text("Save")');
await admin.waitForSelector('text=0244000000');
await admin.screenshot({ path: 'shots/rails-admin-configured.png' });

// user: login, security passkeys section, add money via direct rail, move money
await page.goto(base + '/login');
await page.waitForSelector('text=Sign in with biometrics');
await page.screenshot({ path: 'shots/rails-login.png' });
await page.fill('input[placeholder*="you@example.com"]', 'alice@example.com');
await page.fill('input[type=password]', 'Password123!');
await page.click('form button.btn');
await page.waitForURL('**/app');
await page.goto(base + '/app/settings?tab=security');
await page.waitForSelector('text=Biometric login & payment confirmation');
await page.screenshot({ path: 'shots/rails-security.png' });
await page.goto(base + '/app/add-money');
await page.click('button.tab:has-text("Mobile money")');
await page.locator('.field', { hasText: 'Country' }).locator('select').selectOption('GH');
await page.waitForTimeout(600);
await page.locator('.field', { hasText: 'Mobile money operator' }).locator('select').selectOption('mtn_gh');
await page.waitForSelector('text=no API needed');
await page.fill('input[placeholder="0.00"]', '50');
await page.fill('input[placeholder="+233…"]', '+233244111222');
await page.click('button:has-text("Add 50 GHS")');
await page.waitForSelector('text=Reference');
await page.screenshot({ path: 'shots/rails-momo-instructions.png' });
await page.goto(base + '/app/move');
await page.waitForSelector('text=Move money');
await page.fill('input[placeholder="0.00"]', '12');
await page.fill('input[placeholder="@alice"]', 'bob');
await page.waitForSelector('text=Recipient gets', { timeout: 10000 });
await page.screenshot({ path: 'shots/rails-move.png' });
await page.click('button:has-text("Review & confirm")');
await page.fill('input.pin-input', '1234');
await page.click('.modal button:has-text("Confirm")');
await page.waitForSelector('text=Money delivered', { timeout: 10000 }).catch(() => {});
await page.waitForSelector('.card >> text=completed', { timeout: 10000 });
await page.screenshot({ path: 'shots/rails-move-done.png' });
await page.goto(base + '/app/withdraw');
await page.click('button.tab:has-text("Mobile money")');
await page.waitForSelector('text=Mobile money operator');
await page.screenshot({ path: 'shots/rails-withdraw.png' });
console.log('ERRORS:', errors.length ? errors.join('\n') : 'none');
await browser.close();
