const es: Record<string, string> = {
  'nav.dashboard': 'Panel', 'nav.send': 'Enviar dinero', 'nav.scan': 'Escanear y pagar', 'nav.receive': 'Recibir', 'nav.requests': 'Solicitudes y enlaces', 'nav.addMoney': 'Añadir dinero', 'nav.withdraw': 'Retirar', 'nav.agents': 'Agentes y efectivo', 'nav.remittance': 'Remesas', 'nav.exchange': 'Cambio', 'nav.cards': 'Tarjetas virtuales', 'nav.bills': 'Pago de facturas', 'nav.topup': 'Recarga móvil', 'nav.giftCards': 'Tarjetas regalo', 'nav.p2p': 'Comercio P2P', 'nav.transactions': 'Transacciones', 'nav.referrals': 'Referidos', 'nav.support': 'Soporte', 'nav.settings': 'Ajustes', 'nav.merchant': 'Herramientas de comercio', 'nav.agentTools': 'Herramientas de agente', 'nav.logout': 'Cerrar sesión',
  'common.amount': 'Importe', 'common.currency': 'Moneda', 'common.note': 'Nota', 'common.continue': 'Continuar', 'common.confirm': 'Confirmar', 'common.cancel': 'Cancelar', 'common.save': 'Guardar', 'common.fee': 'Comisión', 'common.total': 'Total', 'common.status': 'Estado', 'common.date': 'Fecha', 'common.search': 'Buscar', 'common.loading': 'Cargando…', 'common.balance': 'Saldo', 'common.pin': 'PIN de transacción', 'common.copy': 'Copiar', 'common.copied': '¡Copiado!', 'common.share': 'Compartir', 'common.back': 'Atrás', 'common.all': 'Todo', 'common.none': 'Nada por aquí todavía',
  'auth.signIn': 'Iniciar sesión', 'auth.signUp': 'Crear cuenta', 'auth.email': 'Correo', 'auth.phone': 'Número de teléfono', 'auth.password': 'Contraseña', 'auth.identifier': 'Correo o teléfono', 'auth.forgot': '¿Olvidaste tu contraseña?', 'auth.otpLogin': 'Entrar con código único', 'auth.noAccount': '¿No tienes cuenta?', 'auth.haveAccount': '¿Ya tienes cuenta?', 'auth.fullName': 'Nombre completo', 'auth.role': 'Tipo de cuenta', 'auth.role.user': 'Personal', 'auth.role.merchant': 'Comercio / empresa', 'auth.role.agent': 'Agente / minorista', 'auth.referral': 'Código de referido (opcional)', 'auth.country': 'País', 'auth.sendCode': 'Enviar código', 'auth.code': 'Código de verificación',
  'dash.welcome': 'Hola de nuevo, {name}', 'dash.totalBalance': 'Saldo total', 'dash.quickActions': 'Acciones rápidas', 'dash.recent': 'Actividad reciente', 'dash.viewAll': 'Ver todo',
  'send.title': 'Enviar dinero', 'send.to': 'Destinatario (@tag, correo o teléfono)', 'send.review': 'Revisar transferencia', 'send.success': '¡Dinero enviado!', 'receive.title': 'Recibir dinero', 'receive.subtitle': 'Deja que otros escaneen este código para pagarte', 'receive.requestAmount': 'Solicitar un importe concreto', 'scan.title': 'Escanear para pagar', 'scan.hint': 'Apunta la cámara a un código QR de BitriPay', 'scan.paste': 'O pega el contenido del QR / enlace de pago',
  'addMoney.title': 'Añadir dinero', 'addMoney.method': 'Método de pago', 'addMoney.card': 'Tarjeta de débito / crédito', 'addMoney.mobileMoney': 'Dinero móvil', 'addMoney.bank': 'Transferencia bancaria', 'addMoney.agent': 'Efectivo en un agente', 'withdraw.title': 'Retirar al banco', 'tx.in': 'Recibido', 'tx.out': 'Enviado',
  'settings.profile': 'Perfil', 'settings.security': 'Seguridad', 'settings.kyc': 'Verificación de identidad', 'settings.language': 'Idioma', 'settings.theme': 'Modo oscuro', 'settings.2fa': 'Autenticación de dos factores', 'settings.pin': 'PIN de transacción', 'settings.password': 'Cambiar contraseña',
  'landing.hero': 'El dinero a la velocidad de un escaneo', 'landing.sub': 'Envía, recibe y acepta pagos con códigos QR. Añade dinero con tarjeta o dinero móvil, paga facturas, envía remesas, cambia divisas y emite tarjetas virtuales, todo desde una sola billetera BitriPay.', 'landing.getStarted': 'Empieza gratis', 'landing.merchant': 'Aceptar pagos',
};
export default es;
