const pt: Record<string, string> = {
  'nav.dashboard': 'Painel', 'nav.send': 'Enviar dinheiro', 'nav.scan': 'Ler QR e pagar', 'nav.receive': 'Receber', 'nav.requests': 'Pedidos e links', 'nav.addMoney': 'Adicionar dinheiro', 'nav.withdraw': 'Levantar', 'nav.agents': 'Agentes e numerário', 'nav.remittance': 'Remessas', 'nav.exchange': 'Câmbio', 'nav.cards': 'Cartões virtuais', 'nav.bills': 'Pagar contas', 'nav.topup': 'Recarga móvel', 'nav.giftCards': 'Cartões presente', 'nav.p2p': 'Negociação P2P', 'nav.transactions': 'Transações', 'nav.referrals': 'Indicações', 'nav.support': 'Suporte', 'nav.settings': 'Definições', 'nav.merchant': 'Ferramentas de comerciante', 'nav.agentTools': 'Ferramentas de agente', 'nav.logout': 'Terminar sessão',
  'common.amount': 'Montante', 'common.currency': 'Moeda', 'common.note': 'Nota', 'common.continue': 'Continuar', 'common.confirm': 'Confirmar', 'common.cancel': 'Cancelar', 'common.save': 'Guardar', 'common.fee': 'Taxa', 'common.total': 'Total', 'common.status': 'Estado', 'common.date': 'Data', 'common.search': 'Pesquisar', 'common.loading': 'A carregar…', 'common.balance': 'Saldo', 'common.pin': 'PIN de transação', 'common.copy': 'Copiar', 'common.copied': 'Copiado!', 'common.share': 'Partilhar', 'common.back': 'Voltar', 'common.all': 'Tudo', 'common.none': 'Ainda nada aqui',
  'auth.signIn': 'Entrar', 'auth.signUp': 'Criar conta', 'auth.email': 'E-mail', 'auth.phone': 'Número de telefone', 'auth.password': 'Palavra-passe', 'auth.identifier': 'E-mail ou telefone', 'auth.forgot': 'Esqueceu a palavra-passe?', 'auth.otpLogin': 'Entrar com código único', 'auth.noAccount': 'Não tem conta?', 'auth.haveAccount': 'Já tem conta?', 'auth.fullName': 'Nome completo', 'auth.role': 'Tipo de conta', 'auth.role.user': 'Pessoal', 'auth.role.merchant': 'Comerciante / empresa', 'auth.role.agent': 'Agente / retalhista', 'auth.referral': 'Código de indicação (opcional)', 'auth.country': 'País', 'auth.sendCode': 'Enviar código', 'auth.code': 'Código de verificação',
  'dash.welcome': 'Bem-vindo de volta, {name}', 'dash.totalBalance': 'Saldo total', 'dash.quickActions': 'Ações rápidas', 'dash.recent': 'Atividade recente', 'dash.viewAll': 'Ver tudo',
  'send.title': 'Enviar dinheiro', 'send.to': 'Destinatário (@tag, e-mail ou telefone)', 'send.review': 'Rever transferência', 'send.success': 'Dinheiro enviado!', 'receive.title': 'Receber dinheiro', 'receive.subtitle': 'Deixe que outros leiam este código para lhe pagar', 'receive.requestAmount': 'Pedir um montante específico', 'scan.title': 'Ler QR para pagar', 'scan.hint': 'Aponte a câmara para um código QR BitriPay', 'scan.paste': 'Ou cole o conteúdo do QR / link de pagamento',
  'addMoney.title': 'Adicionar dinheiro', 'addMoney.method': 'Método de pagamento', 'addMoney.card': 'Cartão de débito / crédito', 'addMoney.mobileMoney': 'Dinheiro móvel', 'addMoney.bank': 'Transferência bancária', 'addMoney.agent': 'Numerário num agente', 'withdraw.title': 'Levantar para o banco', 'tx.in': 'Recebido', 'tx.out': 'Enviado',
  'settings.profile': 'Perfil', 'settings.security': 'Segurança', 'settings.kyc': 'Verificação de identidade', 'settings.language': 'Idioma', 'settings.theme': 'Modo escuro', 'settings.2fa': 'Autenticação de dois fatores', 'settings.pin': 'PIN de transação', 'settings.password': 'Alterar palavra-passe',
  'landing.hero': 'Dinheiro à velocidade de uma leitura', 'landing.sub': 'Envie, receba e aceite pagamentos com códigos QR. Adicione dinheiro por cartão ou dinheiro móvel, pague contas, envie remessas, troque moedas e emita cartões virtuais – tudo numa carteira BitriPay.', 'landing.getStarted': 'Comece grátis', 'landing.merchant': 'Aceitar pagamentos',
};
export default pt;
